name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
            echo "Hola, corazona...!!!"
            echo "Ahora puedo escribir en varias lineas"
      - name: Print goodbye
        run: echo "Chau, corazona...!!!"
